### PR TITLE
Add citation.cff file

### PR DESCRIPTION
**Pull request by camriddell**
https://github.com/econ-ark/REMARK/blob/721aa958794596d9ef506ceb4af1397fc7f17170/REMARKs/DistributionOfWealthMPC.md

### CODE REVIEW

**Comment by alanlujan91** [comment]
I have a question here about authors of the repo, which is a reproduction of a paper, and authors of the paper. Is there a distinction in the citation? @camriddell

**Comment by camriddell** [comment]
@alanlujan91 sorry I misread your original message.

For the specification the authors of a reproduction should be in the first 

image

**Comment by alanlujan91** [comment]
This seems to replace Seb as an author of the repo, though. Is that correct?

**Comment by camriddell** [comment]
@alanlujan91 yes it did. I re-added the reproduction authors from the original CITATION.cff file. Does this look correct to you?

**Comment by alanlujan91** [comment]
@sbenthall might be more qualified to answer this question.

**Comment by sbenthall** [comment]
There was originally the `cstwmpc` repository:
https://github.com/llorracc/cstwMPC

I'm not sure, but it might be that that repo is generated from some other repo, and so doesn't have the fulll development history.

That got replaced by `DistirbutionOfWealth`, which generalized a bit from the original `cstwmpc` paper.

I think @alanlujan91 is right, that the question is about what metadata to include when there is onging maintenance/development of a repository. 

There can be in principle multiple tagged releases of a REMARK and it would make sense for the .cff file to also be versioned.

**Comment by camriddell** [comment]
Agreed here since the .cff file is under version control along with the rest of the repository.

The question still at hand is: who actually contributed to this reproduction? (e.g. what should the up to date, most recent author list .cff file look like).

**Comment by sbenthall** [comment]
My proposal: in addition to the versioned .cff file, or maybe within it, include a changelong tracking who contributed to each version in the history, as well as the current version.

**Pull request merged**
