### PR TITLE
Make binder happy

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by alanlujan91** [comment]
What I mean is that I've already made binder happy, I had to add xarray scipy numpy numba pandas to the environment.yml file because it didn't work without it. But it is already fixed.

**Comment by MridulS** [comment]
Yeah, but I don't think we need to add any of these deps. Just econ-ark@master and ipython should be fine.

**Comment by MridulS** [comment]
and we should try to keep these environment.yml file as small as possible

**Comment by MridulS** [comment]
https://mybinder.org/v2/gh/econ-ark/DistributionOfWealthMPC/make_binder_happy does this work for you?

**Pull request merged**
